### PR TITLE
Added feature in login page and some transitions 

### PR DESCRIPTION
**Pull request by Mujtabaa07**
Added Feature In Login Page Like , It shows the password Strength if its weak or medium or strong while signing-up. And added hover effect on the image , Motivation and Context: This feature allows users to Know there password strength.

## Type of change (login-page-and-hover-effect)
Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?
Tested while logining the page.

# Screenshorts and Videos:

https://github.com/pooranjoyb/popShop/assets/70109255/5f7473de-e7f2-496c-a7b8-3e15832e6940

# Checklist:
give a X on it which is applicable

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @Mujtabaa07! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Review by pooranjoyb — APPROVED** [review]

**Comment by pooranjoyb** [comment]
Fix the conflicts! @Mujtabaa07

**Comment by AjayAsnani** [comment]
Great work @Mujtabaa07 but I guess the password strength should not be visible on Login page it should only be visible on Sign up page.

Because when we sign in then only we have to check the strength.

**Comment by pooranjoyb** [comment]
Do the requested change by the mentors :eyes:
@Mujtabaa07

**Comment by Mujtabaa07** [comment]
> Do the requested change by the mentors 👀 @Mujtabaa07

yes sure

**Comment by pooranjoyb** [comment]
Create a fresh PR. many conflicts here :/
Take a pull from `dev` branch @Mujtabaa07

**Pull request closed without merging**
