### PR TITLE
update cart and when user increase quantity the price also should be …

### LINKED ISSUE #171: [BUG] update price when we increase quantity in cart
### Description

@pooranjoyb 

check this out,
when we increase the quantity the price should also be increased

### Screenshots

image

### PR DESCRIPTION
**Pull request by dhruv8433**
@pooranjoyb 

…increased
[BUG] update price when we increase quantity in cart #171

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #171

## Type of change

Please give a X on it which is applicable

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

- go to cart and try to increase quantity of product

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Requred)_**

# Screenshorts and Vedios:

https://github.com/pooranjoyb/popShop/assets/114583978/c1493b69-ed4c-424a-ab45-14d01052b11e

# Checklist:
give a X on it which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @dhruv8433! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhruv8433** [comment]
@pooranjoyb 

please add `level` label and merge it

**Comment by pooranjoyb** [comment]
Hii @dhruv8433 I was expecting a PR for #109 
This feature is not on the priority list. Also doesn't need DB access. I added you on team for #109 Please do that first.

Also there are many build errors. I'd suggest to work on this later.
image

**Comment by pooranjoyb** [comment]
You even mentioned it here https://github.com/pooranjoyb/popShop/issues/171#issuecomment-2146940329

**Comment by dhruv8433** [comment]
@pooranjoyb 

Sorry i think i misunderstand
I think you said #109 merged

**Comment by dhruv8433** [comment]
I will completed #109 till tommorrow

**Comment by pooranjoyb** [comment]
No issues, but yeah #109 is priority! @dhruv8433

**Pull request closed without merging**
