### PR TITLE
search based on product name

### PR DESCRIPTION
**Pull request by Varsani2520**
user can able to search based on product name ,if search product is exist in product database then display that products information

Fixes # (issue)
#318 

## Type of change

Please give a X on it which is applicable

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Requred)_**

# Screenshots and Videos:
image

Give screenshots and video of the changes you made

# Checklist:
Give a X on, which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Varsani2520** [comment]
@pooranjoyb ,i solved the #318 ,now you can review it and merged it

**Comment by Varsani2520** [comment]
@pooranjoyb ,merged it

**Comment by pooranjoyb** [comment]
> @pooranjoyb ,i solved the #318 ,now you can review it and merged it

[screen-recorder-wed-jul-10-2024-22-41-26.webm](https://github.com/pooranjoyb/popShop/assets/90945182/3176d11b-e3d5-457d-8edc-95cc9f80c74a)

You see there is a bug, after searching something and clearing it out we cannot see all the products :/

**Review by Varsani2520 — COMMENTED** [review]
all check passed

**Comment by Varsani2520** [comment]
@pooranjoyb ,check it  

https://github.com/pooranjoyb/popShop/assets/137641079/8c347f8d-b8cf-4828-a002-8a9ec4fae45a

**Pull request merged**
