### PR TITLE
added buttons on Products page and home screen

### LINKED ISSUE #55: [FEATURE] Add 'Buy Now' button and 'Add to Cart' icon on the Products Page
In the below Products Page, there should be a 'Buy Now' Button and 'Add to cart' icon to each product, similar to modern websites.
Customer finds this feature effecient as going into the specific product page and then adding it to cart / buying it, is a bit lengthy process. 
I have been working on similar project and can get this done ASAP. 
I would like to contribute to this task under GSSOC '24

Screenshot (195)

### PR DESCRIPTION
**Pull request by Amitooo1**
I've added 'Buy Now' and 'Add to Cart' buttons to the product pages, ensuring they align with the website's theme and maintain good color contrast for accessibility.
Fixes #55 

This pull request introduces 'Buy Now' and 'Add to Cart' buttons that are visually consistent with the website's design and optimized for various screen sizes.
image

My code follows the style guidelines of this project
I have performed a self-review of my code
I have commented my code, particularly in hard-to-understand areas
My changes generate no new warnings
New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @Amitooo1! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
I'd say to use an icon for `Add to Cart` rather than the button. @Amitooo1

**Comment by Amitooo1** [comment]
okay @pooranjoyb, changing that button to an icon.

**Comment by Amitooo1** [comment]
image
@pooranjoyb how does this looks?

**Comment by Mahitej28** [comment]
@Amitooo1 firstly the `cart icon` is not clickable and secondly,

image
 You see there is too much space between the cart icon and the text description, just work on it and better u share a figma design file with me rather then updating the code directly

**Comment by Mahitej28** [comment]
@Amitooo1 there are some changes made in the main branch I suggest you take a pull from `dev` so that I can preview it.

**Comment by Amitooo1** [comment]
Sure @Mahitej28

**Comment by Mahitej28** [comment]
> @Amitooo1 firstly the `cart icon` is not clickable and secondly,
> 
> image
>  You see there is too much space between the cart icon and the text description, just work on it and better u share a figma design file with me rather then updating the code directly


@Amitooo1 give your updates by EOD

**Comment by Amitooo1** [comment]
@Mahitej28 frontend is done and cart button is responding on clicks as shown below
image

for further functionality of add to cart button a lot of backend need to be develop as prior functionalities of add to cart is limited to a popup message only. For that i can raise a seperate issue.

**Pull request merged**
