### PR TITLE
Resolved Update-Profile-Details

### LINKED ISSUE #281: [BUG] Update Profile Details
### Description

Okay so when we `Signup` using Google OAuth, the gender and phone number is not fetched from the OAuth response. We need to allow the user to manually update these in their profile. 

### Screenshots

image

### Any additional information?

Currently `Edit Profile` doesnot allow change in `Gender` and `Phone Number`, we need to update this and change the respective userData in Supabase. 

image

### PR DESCRIPTION
**Pull request by bhuvangoel04**
Resolved the issue that gender was not getting updated on edit profile. Added the feature to edit gender.

Fixes #281

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @bhuvangoel04! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Hii @bhuvangoel04 I can see that you're not restricting the Gender to `Male` & `Female` only. Even if I try to save Hii Hello (or any other string) it gets saved. 

You can try using a dropdown option to choose (Male or Female) that'll restrict the user to add strings in gender.

**Comment by bhuvangoel04** [comment]
Ok I will make changes to it.

**Comment by bhuvangoel04** [comment]
Should I close this pull request then and make another one?

**Comment by pooranjoyb** [comment]
> Should I close this pull request then and make another one?

No need, same branch me push karoge toh idhar hi add ho jayega. I mean it's upto you. Just drop a PR by EOD.

**Comment by bhuvangoel04** [comment]
I have committed the required changes, please check it out.

**Review by pooranjoyb — APPROVED** [review]

**Comment by pooranjoyb** [comment]
Awesomr work @bhuvangoel04 🚀 
Please don't forget to Star the repository!

**Comment by bhuvangoel04** [comment]
Thank you 
I always star a repository before forking it.

**Pull request merged**
