### PR TITLE
Animation added to HomePage

### PR DESCRIPTION
**Pull request by dev04sa**
@pooranjoyb as required Animations added to HomePage by using Framer-motion .
Issue #38 also Resolved .
Kindly Review The PR.
Here Sample Video is Provided : -

https://github.com/pooranjoyb/popShop/assets/129666293/d009ca18-177b-4500-a6e0-e538514e846c

### CODE REVIEW

**Comment by pooranjoyb** [comment]
Fix this. @dev04sa  

image

**Comment by dev04sa** [comment]
> Fix this. @dev04sa
> 
> image

@pooranjoyb its seems like what freepik img url have you used earlier that link is not working.
Screenshot 2024-05-13 223703

if you wish I can replace image with another image.

**Comment by pooranjoyb** [comment]
Replace with a similar type of image

**Comment by dev04sa** [comment]
Here is replaced Image 
Screenshot 2024-05-13 224418

**Pull request closed without merging**
