### PR TITLE
[FEATURE] Added a Navbar

### PR DESCRIPTION
**Pull request by Vedant5751**
Added a Floating Navbar
Smooth Scrolling To Components - Collections, Products, Footer
Below are the screenshots
Screenshot 2024-05-16 233804
Screenshot 2024-05-16 233845
Screenshot 2024-05-16 233859

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @Vedant5751! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Vedant5751** [comment]
@pooranjoyb Hey! Please review the PR.

**Comment by Vedant5751** [comment]
Sorry accidently closed it

**Comment by pooranjoyb** [comment]
Hii can you use the Glassmorphism UI, rather than a solid color? @Vedant5751

**Comment by Vedant5751** [comment]
Which one do you prefer?
White/Transparent
Screenshot 2024-05-17 141236
Screenshot 2024-05-17 141243
Screenshot 2024-05-17 141251

Lighter Green
Screenshot 2024-05-17 141431
Screenshot 2024-05-17 141440
Screenshot 2024-05-17 141446

More Opaque Green
Screenshot 2024-05-17 141824
Screenshot 2024-05-17 141829
Screenshot 2024-05-17 141835

**Comment by Mahitej28** [comment]
@Vedant5751 I suggest that you don't fix the navbar at the top, because its covering all section's heading.

**Comment by Vedant5751** [comment]
@Mahitej28 so u just want a simple broad wrapper at the top? Do u want me to include this to ur existing navbar (with pop shop.com and cart icon) or make a navbar above that part?

**Comment by Mahitej28** [comment]
> @Mahitej28 so u just want a simple broad wrapper at the top? Do u want me to include this to ur existing navbar (with pop shop.com and cart icon) or make a navbar above that part? or just remove the sticky attribute from my navbar?

Just remove the sticky attribute because its overlapping with the heading of different sections while scrolling.

**Comment by Vedant5751** [comment]
> > @Mahitej28 so u just want a simple broad wrapper at the top? Do u want me to include this to ur existing navbar (with pop shop.com and cart icon) or make a navbar above that part? or just remove the sticky attribute from my navbar?
> 
> Just remove the sticky attribute because its overlapping with the heading of different sections while scrolling.

its done , check the new pull request i made

**Pull request closed without merging**
