### PR TITLE
remove item from cart success

### LINKED ISSUE #222: [Feature] Remove item from cart as well supabase
### Description

@pooranjoyb 

we can add remove icon in cart and when user click on that 
item should be removed from redux as well supabase 

### Screenshots

image

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by dhruv8433**
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

@pooranjoyb 

[Feature] Remove item from cart as well supabase #222

Fixes #222

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

- add some items in cart
- try to remove particular one

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Requred)_**

# Screenshorts and Vedios:

https://github.com/pooranjoyb/popShop/assets/114583978/56f8fee6-ddc1-42c1-bf73-d2969390b81d

give screenshorts and vedio of the changes you made

# Checklist:
give a X on it which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @dhruv8433! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhruv8433** [comment]
@pooranjoyb 

kindly please check this and merge it

**Comment by pooranjoyb** [comment]
Nice work @dhruv8433 🚀 

Just show that cart is empty when there are no items in cart :)
image

**Comment by dhruv8433** [comment]
@pooranjoyb 

ok i will add empty state

**Comment by dhruv8433** [comment]
@pooranjoyb 

image

image

addde empty state for cart

**Comment by dhruv8433** [comment]
Thank you :)

**Pull request merged**
