### PR TITLE
dynamic image rendering using supabase

### PR DESCRIPTION
**Pull request by Yogesh-ok55**
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (152)

## Type of change
using supabase images is being rendered from dynamically before it was statically stored in folder , additionally i have also added Loader in case of any delay 

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**
->i have tested it many times to see its efficiency and it is working well and fast in case of delay i have also added loader

# Checklist:
give a X on it which is applicable

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @Yogesh-ok55! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Fix the build errors. Run `npm run build` @Yogesh-ok55

**Comment by Yogesh-ok55** [comment]
> Fix the build errors. Run `npm run build` @Yogesh-ok55

using npm run build i have fixed all build errors now what should i do

**Comment by Mahitej28** [comment]
@Yogesh-ok55 there are still some build errors check again, the deployment has failed

**Comment by Yogesh-ok55** [comment]
i have made some recent changes please consider them...

**Comment by pooranjoyb** [comment]
Hey @Yogesh-ok55 what i can see is you are creating a table to store the images and fetching just the link and rendering them. I guess this is not how it is supposed to work. You were supposed to use the supabase storage for it. 

Check the docs for supabase storage, we need to create a bucket to store the images. please let us know if you aren't comfortable with this. We will reassign accordingly.

**Comment by pooranjoyb** [comment]
Do let us know by eod if you wanna continue with this. @Yogesh-ok55

**Pull request closed without merging**
