### PR TITLE
make admin dashboard responsive

### LINKED ISSUE #347: [BUG] Make Dashboard Responsive
### Description

@pooranjoyb 

we can make dashboard ui responsive so it have better view in responsive devices

### Screenshots

image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

Chrome

### PR DESCRIPTION
**Pull request by dhruv8433**
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

@pooranjoyb 

[BUG] Make Dashboard Responsive #347

Fixes #347 (issue)

## Type of change

Please give a X on it which is applicable

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Requred)_**

# Screenshots and Videos:

Give screenshots and video of the changes you made

https://github.com/user-attachments/assets/362d3fdd-d5a0-4551-91a4-e45b61974779

# Checklist:
Give a X on, which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @dhruv8433! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhruv8433** [comment]
@pooranjoyb 

check this and merge it

**Comment by pooranjoyb** [comment]
can we use the same navbar on admin dashboard too? I mean the profile icon wala button?

**Comment by dhruv8433** [comment]
@pooranjoyb 

image

**Comment by dhruv8433** [comment]
i added navbar that have profile icon 
please inform me if you need any modifications

**Comment by dhruv8433** [comment]
@pooranjoyb 

please check this and tell me if you need any modifications

**Comment by pooranjoyb** [comment]
> @pooranjoyb
> 
> please check this and tell me if you need any modifications

Hey @dhruv8433 see this is a bug, isn't it?

image

I guess you need to create a new Navbar Component inside the Admin directory. That should have the navigations for admin-routes

**Comment by dhruv8433** [comment]
Got it

**Comment by dhruv8433** [comment]
@pooranjoyb 

I am removing sidebar and create new navbar for admin panel

**Comment by dhruv8433** [comment]
@pooranjoyb 
 
i updated my code and add admin navigation 

image

image

**Comment by pooranjoyb** [comment]
image

Fix this too :/

**Comment by dhruv8433** [comment]
@pooranjoyb 
solved

**Comment by dhruv8433** [comment]
image

**Comment by dhruv8433** [comment]
@pooranjoyb 

please check this and merge it

**Comment by pooranjoyb** [comment]
> @pooranjoyb
> 
> please check this and merge it

Bro please add all the routes for admin :/

**Comment by dhruv8433** [comment]
@pooranjoyb 

Can you please tell me what route i have to add 

I think i added all sidebar routes

**Comment by pooranjoyb** [comment]
> @pooranjoyb
> 
> Can you please tell me what route i have to add
> 
> I think i added all sidebar routes

I mean the transactions, orders and add products one. same, jesa navbar pe dala hua hai :/

**Comment by dhruv8433** [comment]
@pooranjoyb 

check this and tell me if you need any modification 
actually, i removed the sidebar and created separate navbar for the admin panel
also, make it a responsive burger menu

https://github.com/user-attachments/assets/07309dea-44ad-49b5-a299-5e3e11cc5db2

**Comment by pooranjoyb** [comment]
Cool, ise theek kar do bss

image

@dhruv8433

**Comment by dhruv8433** [comment]
@pooranjoyb 

make it full width in responsive devices

image

image

**Comment by dhruv8433** [comment]
@pooranjoyb 

please check this and merge it

**Pull request merged**
