### PR TITLE
Added functionality to buy now button

### LINKED ISSUE #288: [Feature] Adding functionality to the buy now button.
### Description

When the user clicks on Buy now button, the user is redirected tot the checkout page.

### Screenshots

image

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by bhuvangoel04**
Functionality for Buy now has been added. When user clicks on buy now, only the current product will be bought and it will not affect the cart.

Fixes #288 

## Type of change

# How Has This Been Tested?

**Added a product to cart and used buy now for another product.**

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @bhuvangoel04! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
why did you comment out the entire file?

**Comment by bhuvangoel04** [comment]
Just some problem sorry for that.

**Comment by bhuvangoel04** [comment]
But the code runs perfectly.

**Comment by pooranjoyb** [comment]
Ok mentors will review and merge if everything's fine.

**Comment by bhuvangoel04** [comment]
> why did you comment out the entire file?

Should I make another commit to remove the commented part?

**Pull request merged**
