### PR TITLE
Fixed bugs

### LINKED ISSUE #259: [BUG]: No checks applicable
### Description

There are two bugs I would like to fix. 
1. When the product is added to the cart, there is no requirement for size. Without the size being selected, it is being added to the cart. I want to add a validation check for that.
2. After checkout, the cart should be empty. Even after checkout, the cart shows all the items which were just purchased. I would like to add a validation check for that as well.

Kindly assign me this issue under GSSoC'24 with an appropriate level.

### Screenshots

Bug1
image

Bug2
image
image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

Chrome

### PR DESCRIPTION
**Pull request by abckhush**
Fixed 2 bugs.
1. Now it is mandatory to add a size before adding an item to the cart.
2. After the checkout, all items are cleared from the cart.

Fixes #259 

## Type of change

Please give a X on it which is applicable

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- (mentioned in the issue number)

# How Has This Been Tested?

Test A: Mandatory Size Selection:
- Navigate to the product page.
- Attempt to add an item to the cart without selecting a size.
- Verify that an error message or indication prevents the item from being added.
- Select a size and then add the item to the cart.
- Confirm that the item is successfully added to the cart.

Test B: Clear Cart After Checkout:
- Add multiple items to the cart.
- Proceed to the checkout page.
- Complete the checkout process.
- Verify that a confirmation message is displayed, and the cart is emptied.
- Navigate back to the cart page to ensure it is empty.

# Screenshots and Videos:

BUG 1 FIX
Screenshot 2024-06-22 211743

BUG 2 FIX
image
image
image

# Checklist:
give a X on it which is applicable

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @abckhush! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
never push env variables

**Comment by abckhush** [comment]
Ok. I have deleted it.

**Comment by abckhush** [comment]
Hi @pooranjoyb Kindly merge this.

**Comment by abckhush** [comment]
@pooranjoyb merge this pls

**Review by pooranjoyb — APPROVED** [review]

**Pull request merged**
