### PR TITLE
fixes issue #306

### PR DESCRIPTION
**Pull request by Tanishashrivas**
Corrected the payment unit from $ to rupees.

Fixes # (issue)
https://github.com/pooranjoyb/popShop/issues/306

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Requred)_**

# Screenshots and Videos:

Give screenshots and video of the changes you made

# Checklist:
Give a X on, which is applicable

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @Tanishashrivas! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Hey @Tanishashrivas pls do the changes for #302 in this same PR only.

**Comment by Tanishashrivas** [comment]
> Hey @Tanishashrivas pls do the changes for #302 in this same PR only.

Sir, i can do that but will i get points for this level1 issue and level2 issue?

**Comment by Tanishashrivas** [comment]
made new pr with both issues fixed

**Pull request closed without merging**
