### PR TITLE
added `orders` while user checkout their cart and remove cart items a…

### LINKED ISSUE #233: [Feature] Make Payment option functionals
### Description

@pooranjoyb 

we can make this payment option functionals
we can add stripe payment gateway to take card info and make payment in `test` mode

### Screenshots

something like this

image

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by dhruv8433**
…fter `checkout`

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

@pooranjoyb 

[Feature] Make Payment option functionals #233

Fixes #233 (issue)

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

- go to checkout and see supabase orders table

**_Test B Describe here (if Requred)_**

# Screenshorts and Vedios:

https://github.com/pooranjoyb/popShop/assets/114583978/f0585ac3-9245-422c-84ec-4d5a3fdea808

give screenshorts and vedio of the changes you made

# Checklist:
give a X on it which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @dhruv8433! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhruv8433** [comment]
please inform me if you want any modifications

**Comment by pooranjoyb** [comment]
Replace the `Close` button with `Continue Shopping` with the `my-green` button. This button should redirect user to `/home/shop` @dhruv8433

**Comment by dhruv8433** [comment]
@pooranjoyb 

1. bg-my green

image

2. remove quantity from product detailed

image

**Comment by pooranjoyb** [comment]
Did you do this? @dhruv8433 

> Also i can see that you are calling the method to update cart quantity and price on each quantity update. This should not be done as this leads to recurrent requests to the db. Optimize this to make sure that you make only 1 api call to update the quantity and price when user clicks on Place Order.

**Comment by dhruv8433** [comment]
@pooranjoyb 

i just removed quantity buttons from detailed product 
now it's only in cart

**Comment by pooranjoyb** [comment]
Update this API request wala thing. Read the tasks.

**Comment by dhruv8433** [comment]
ok got it

**Comment by dhruv8433** [comment]
@pooranjoyb 

now you can check this,

- i updated code now when user change quantity it only set in local `redux store`
- when usesr click on place order than only it send to supabase and also set their quantity in that

image

after checkout or place order

image

**Comment by dhruv8433** [comment]
@pooranjoyb 

please check this and merge it

**Comment by pooranjoyb** [comment]
There are still some bugs, please cross check the deployment. 
These are the issues that i've found :
- Sometime, even after i click checkout i cannot see the updated total summary.
- quantity is changing but not updating. (I guess go with the previous flow. that'll do.)

I suggest you to revert the changes. this api call wala, keep this aside for a moment.

**Comment by dhruv8433** [comment]
@pooranjoyb 

i revert the changes

**Comment by dhruv8433** [comment]
@pooranjoyb 

please check this and let me inform if you need any modifications

**Comment by pooranjoyb** [comment]
Cool! awesome work @dhruv8433 🚀

**Pull request merged**
