### PR TITLE
Feat: Enter Triggers Login

### LINKED ISSUE #149: [Feature] `Enter` should also trigger `Login`
### Description

Currently we had to click on `Login` Button, we should also be able to Login after filling details and then `Enter Button`

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by yash28goyal**
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
The form was not submitting when the user pressed the Enter key, which is a common expectation in web forms. This could lead to a poor user experience and confusion.

Motivation and Context
User Experience: Users typically expect pressing Enter to submit forms. Implementing this ensures intuitive interaction.
Form Consistency: Handling submission through the onSubmit event of the form element is standard practice, improving code maintainability and readability.

Fixes #149 

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

Test Case: Ensure the form submits correctly when pressing the Enter key.

Steps:
- Navigate to the Sign Up page.
- Fill in the username, email, and password fields.
- Press the Enter key.
- Verify that the user is redirected to the Login page with fields auto-filled.
- Press Enter again on the Login page.
- Verify that the user is redirected to the Home page.

> Expected Outcome: The form should submit and navigate to the respective pages upon pressing Enter.

**_Test B Describe here (if Requred)_**

Test Case: Ensure the form submits correctly when clicking the Sign Up or Login button.

Steps:

- Navigate to the Sign Up page.
- Fill in the username, email, and password fields.
- Click the Sign Up button.
- Verify that the user is redirected to the Login page with fields auto-filled.
- Click the Login button.
- Verify that the user is redirected to the Home page.

> Expected Outcome: The form should submit and navigate to the respective pages upon clicking the button.

# Screenshorts and Vedios:

https://github.com/pooranjoyb/popShop/assets/123368055/caaed2b4-f494-4179-b49e-890a81ac2ede

# Checklist:
give a X on it which is applicable

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @yash28goyal! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
There are build errors. Always run `npm run build` to ensure that there are no build errors!

image


Fix them :/ @yash28goyal

**Comment by yash28goyal** [comment]
Please check this again.

**Review by pooranjoyb — APPROVED** [review]

**Comment by pooranjoyb** [comment]
Seems Good. Nice work @yash28goyal

**Pull request merged**
