### PR TITLE
added new feature of styling by ChelseaSingla1

### PR DESCRIPTION
**Pull request by Chelseasingla1**
I made changes according to #19 issue
I added a new button in Routes.tsx for styling
And made a new page Styling path is /home/styling

image
image

image

First there is no styled outfit
Once user click on above products to style different clothing's it would be visible like this:
image

Here is the video tutorial:
[**Video Demonstration how this styling page actually works**](https://youtu.be/FdBeZWbNUvU)

We can make changes by adding multiple images mean time i have only added three images

### CODE REVIEW

**Comment by Chelseasingla1** [comment]
@Mahitej28 Hi can you please check, checks got failed again.

**Comment by pooranjoyb** [comment]
Check the build, it still has errors :/
Fix that and run `npm run build` before pushing :)

**Comment by Chelseasingla1** [comment]
> Check the build, it still has errors :/ Fix that and run `npm run build` before pushing :)

okay sure i will check it.

**Comment by Mahitej28** [comment]
@Chelseasingla1 If you are not able to solve it send a screenshot of the build error

**Comment by Mahitej28** [comment]
@Chelseasingla1 send screenshot of error if you aren't able to solve it

**Comment by Chelseasingla1** [comment]
> @Chelseasingla1 If you are not able to solve it send a screenshot of the build error

@Mahitej28 yes thankyou i guess it will work now i was not doing that build step i guess thats why it got failed.

**Pull request closed without merging**
