### PR TITLE
ClothingStyler page added by ChelseaSingla1

### PR DESCRIPTION
**Pull request by Chelseasingla1**
I made changes according to #19 issue
I added a new button in Routes.tsx for styling
And made a new page Styling path is /home/styling

image
image

image

First there is no styled outfit
Once user click on above products to style different clothing's it would be visible like this:
image

Here is the video tutorial:
[**Video Demonstration how this styling page actually works**](https://youtu.be/FdBeZWbNUvU)

We can make changes by adding multiple images mean time i have only added three images

### CODE REVIEW

**Comment by pooranjoyb** [comment]
Please review @Mahitej28

**Comment by Mahitej28** [comment]
> Please review @Mahitej28
Sure will review it by eod

**Comment by Mahitej28** [comment]
Also @Chelseasingla1 make your images clickable like they on click they should open product details and price costing

**Review by Mahitej28 — COMMENTED** [review]
Make images clickable so they redirect to product details

**Comment by Chelseasingla1** [comment]
> @Chelseasingla1 make your images clickable like they on click they should open product details and cost of product.
> 
> Rest all thing looks good to me good job!

Okay sure thankyou, I will try to do it.

**Comment by Chelseasingla1** [comment]
> Make images clickable so they redirect to product details

Okay

**Comment by Mahitej28** [comment]
@Chelseasingla1 updates?

**Comment by Chelseasingla1** [comment]
> @Chelseasingla1 updates?

@Mahitej28 Yes i will update it by today

**Comment by Chelseasingla1** [comment]
> @Chelseasingla1 updates?



> @Chelseasingla1 updates?

@Mahitej28 hi can i delete my current repo because i am facing some issues

**Comment by Mahitej28** [comment]
Yes @Chelseasingla1 there are merge conflicts too kindly try to solve that

**Comment by Chelseasingla1** [comment]
> Yes @Chelseasingla1 there are merge conflicts too kindly try to solve that. Before merging take pull from master and dev

@Mahitej28 okay will do that asap

**Comment by Mahitej28** [comment]
@Chelseasingla1 updated I can still see the merge conflicts, if you are facing the issue DM me on discord

**Comment by Chelseasingla1** [comment]
> @Chelseasingla1 updates? I can still see the merge conflicts, if you are facing the issue DM me on discord



> @Chelseasingla1 updates? I can still see the merge conflicts, if you are facing the issue DM me on discord

@Mahitej28 yes i am working on it

**Comment by Mahitej28** [comment]
@Chelseasingla1 give updates or else, I will assign this to someone else by EOD. You still have not resolved the merge conflicts, it shouldn't take so much time.

**Comment by Chelseasingla1** [comment]
> @Chelseasingla1 give updates or else, I will assign this to someone else by EOD. You still have not resolved the merge conflicts, it shouldn't take so much time.

yes i will update it by eod

**Pull request closed without merging**
