### PR TITLE
Real time data in dashboard

### PR DESCRIPTION
**Pull request by Varsani2520**
in admin dashboard display realtime data 

Fixes # (issue)
#342 
## Type of change

Please give a X on it which is applicable

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# Screenshots and Videos:

image

# Checklist:
Give a X on, which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x]I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @Varsani2520! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Varsani2520** [comment]
@pooranjoyb , review it and if you want to any changes then inform me

**Comment by Varsani2520** [comment]
Recent Custome ,store overview and checkout data comes from supabase

**Comment by pooranjoyb** [comment]
> Recent Custome ,store overview and checkout data comes from supabase

Okay do one thing, list down the features you integrated in Admin Dashboard. @Varsani2520

**Comment by Varsani2520** [comment]
@pooranjoyb 
i fetched data from supabase :

list are:
Recent Customer ,
store overview and 
checkout data

**Comment by Varsani2520** [comment]
@pooranjoyb ,please give me update 
if you have any query then tell me i solved that

**Comment by Varsani2520** [comment]
@pooranjoyb ,any update @pooranjoyb

**Comment by Varsani2520** [comment]
@pooranjoyb give the response

**Comment by pooranjoyb** [comment]
> @pooranjoyb give the response

Hey @Varsani2520 Really sorry I was traveling for few days. :/

**Pull request merged**
