### PR TITLE
Checkout Page Developed

### LINKED ISSUE #191: [UI] Checkout Page UI
### Create a Checkout Page that will have the following.

- Billing Details is not required coz we already have that in cart.
- Just the payment option is good. Rest everything remains same.
- Make sure it is mobile responsive.

### Screenshot

image

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by BHS-Harish**
Checkout page developed as static as per the given UI Design . Once we can easily setup dynamically once cart section is over.

**Fixes #191** 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
- [x] Checked on various browsers
- [x] Responsiveness checked 

# Screenshot : 

image

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @BHS-Harish! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by BHS-Harish** [comment]
Hey @pooranjoyb @AjayAsnani @Mahitej28 

Please review my request and provide feedback If any changes.

**Comment by AjayAsnani** [comment]
q1

Everything is proper just can you make 1 small change the individual price should also be displayed on the right side where qty and total price is there @BHS-Harish

**Comment by BHS-Harish** [comment]
Hey @AjayAsnani 

Changes made.

**Comment by pooranjoyb** [comment]
> Hey @AjayAsnani @pooranjoyb @Mahitej28
> 
> Changes made.

Awesome contribution @BHS-Harish 🚀

**Pull request merged**
