### PR TITLE
[Feature] Adding an AI Chatbot to the Website

### LINKED ISSUE #315: [Feature] Adding an AI Chatbot to the Website
### Description

Integrate an AI-powered chatbot into the website to enhance user interaction, provide instant support, and improve overall user experience.

Chatbot Functionality:
Answer common user queries
Provide information about our services/products
Assist users with navigation on the website

Expected Outcomes:
Improved user engagement and satisfaction
Reduced response time for user inquiries
Enhanced ability to gather user data for future improvements

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by sanskritisahu21**
Fixes #315

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Ensure that the latest code is deployed to the live server.

# Screenshots and Videos:

image

# Checklist:
Give a X on, which is applicable

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @sanskritisahu21! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by sanskritisahu21** [comment]
@pooranjoyb You can check Chatbot flow in flow file.

**Comment by pooranjoyb** [comment]
Hey @sanskritisahu21 everything looks good, just remove the `.env.local` file from github and push a commit

**Comment by sanskritisahu21** [comment]
@pooranjoyb Done. Now please merge the PR.

**Review by pooranjoyb — APPROVED** [review]

**Comment by pooranjoyb** [comment]
> @pooranjoyb Done. Now please merge the PR.

Nice work @sanskritisahu21

**Comment by sanskritisahu21** [comment]
@pooranjoyb Thankyou

**Pull request merged**
