### PR TITLE
Dynamic filter opetion on products

### LINKED ISSUE #246: [Feature] Apply filter in products
### Description

@pooranjoyb 

we can apply filter and based on that the products will be display

### Screenshots

image

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by dhruv8433**
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

[Feature] Apply filter in products #246

Fixes #246 (issue)

- changed $ to ₹ in product privce at home page and products page
- remove size option from filter
- apply filter based on price

## Type of change

Please give a X on it which is applicable

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?
- go to products page and apply any price filter

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Requred)_**

# Screenshorts and Vedios:

give screenshorts and vedio of the changes you made

https://github.com/pooranjoyb/popShop/assets/114583978/33c0d46c-84d0-4e73-aee8-41030e719ec5

# Checklist:
give a X on it which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @dhruv8433! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhruv8433** [comment]
@pooranjoyb 

please check this and merge it

**Comment by pooranjoyb** [comment]
Do the changes on clicking the `Apply` button. Doing it real-time doesnot makes sense when we have the `Apply` button there.

**Comment by dhruv8433** [comment]
Ok got it

**Comment by dhruv8433** [comment]
@pooranjoyb 

now you can check this

**Review by pooranjoyb — APPROVED** [review]

**Comment by pooranjoyb** [comment]
there are some bugs, please fix them.

after clicking the apply filters, next time it doesnot depend on whether i click the apply button, but shows them in real time. Also when no filters are selected all products dissapear. it should show all by default.

**Comment by dhruv8433** [comment]
ok i will check that

**Comment by dhruv8433** [comment]
@pooranjoyb 

i updated code please check this

**Comment by pooranjoyb** [comment]
Nice work @dhruv8433 🚀

**Pull request merged**
