### PR TITLE
Product add in admin panel

### PR DESCRIPTION
**Pull request by Varsani2520**
in admin panel ,admin user able to add product detail in supabase using fill the form 

Fixes # (issue)
#303 

## Type of change

Please give a X on it which is applicable

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?
fill the form and clic on button then that data add in supabase product table 

# Screenshots and Videos:
image

and this is supabase image:
image

# Checklist:
Give a X on, which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @Varsani2520! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Varsani2520** [comment]
@pooranjoyb ,check it and if you need any changes then tell me

**Comment by pooranjoyb** [comment]
> @pooranjoyb ,check it and if you need any changes then tell me

Hey @Varsani2520 I guess there's a misunderstanding, please read the tasks properly. We should be able to upload the image not add the link. Please research onto this.

See this should be the workflow : 
- I go to `Add Products` 
- Upload an image from from local system. 
- This image should be saved to the Bucket
- You need to fetch the image's link from bucket
- and then add it to the `Products` Table.

Please lemme know if you have any doubts :)

**Comment by Varsani2520** [comment]
hi can you help me in this: when i upload the img then display error msg:

12:21:46.630 Error uploading image: 
Object { statusCode: "403", error: "Unauthorized", message: "new row violates row-level security policy" }
AddProduct.tsx:37:14

**Comment by pooranjoyb** [comment]
> hi can you help me in this: when i upload the img then display error msg:
> 
> 12:21:46.630 Error uploading image: Object { statusCode: "403", error: "Unauthorized", message: "new row violates row-level security policy" } AddProduct.tsx:37:14

Hey @Varsani2520 It was due to `row-level-security` I've disabled it now. It will work now I guess. 

image

**Comment by Varsani2520** [comment]
@pooranjoyb ,same error

**Review by Varsani2520 — COMMENTED** [review]
image uploaded sucessfully in image bucket

**Comment by pooranjoyb** [comment]
Hii @Varsani2520 please check for the deployment error. Run `npm run build` in local system to check for errors.

**Comment by Varsani2520** [comment]
@pooranjoyb ,now check it

**Comment by Varsani2520** [comment]
image
this is image for upload a image

**Comment by pooranjoyb** [comment]
Hey @Varsani2520 just one last task, upload wala sahi  nhi dikh rha hai. Can u use daisy UI image upload component??

**Comment by Varsani2520** [comment]
@pooranjoyb ,
i add the daisy ui for upload cpmponent how is it ?
image

**Comment by Varsani2520** [comment]
if you want to any changes tell me i can do it

**Comment by pooranjoyb** [comment]
> if you want to any changes tell me i can do it

No this looks good :) 🚀 
Nice work @Varsani2520

**Pull request merged**
