### PR TITLE
add subscribe feature

### LINKED ISSUE #284: [Feature] Subscription Feature
### Description

Integrate an API (use a template) to mail users that they've been subscribed to PopShop and also save the subscribers information in supabase.

### Screenshots

image

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by dhruv8433**
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

@pooranjoyb 

[Feature] Subscription Feature #284

Fixes #284 (issue)

please add your keys here: 

image

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Requred)_**

# Screenshots and Videos:

image

image

Give screenshots and video of the changes you made

# Checklist:
Give a X on, which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @dhruv8433! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhruv8433** [comment]
@pooranjoyb 

kindly please check this and merge it

**Comment by pooranjoyb** [comment]
> @pooranjoyb
> 
> kindly please check this and merge it

Hii @dhruv8433 is the mail received to the inbox?

**Comment by dhruv8433** [comment]
image

build success in my local repo
can you please provide me deployment error

**Comment by pooranjoyb** [comment]
image

if you are in linux, make sure that rollup dependency is there in `package.json`

**Comment by dhruv8433** [comment]
@pooranjoyb 

now you can merge it

**Comment by dhruv8433** [comment]
@pooranjoyb

kindly please check this and merge it

**Comment by pooranjoyb** [comment]
> @pooranjoyb
> 
> kindly please check this and merge it

Can you lemme know which service are we using?

**Comment by dhruv8433** [comment]
@pooranjoyb 

emailjs

**Review by pooranjoyb — APPROVED** [review]

**Pull request merged**
