### PR TITLE
Feature:-Animated Loading page

### LINKED ISSUE #68: Animated loading page
I want to add an animated loading page something like this at the beginning of the page.

loader

### PR DESCRIPTION
**Pull request by Mayur-666**
The animated Loading page files have been added to components folder.
Closes #68

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @Mayur-666! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Mayur-666** [comment]
@pooranjoyb  I have pushed the Loader files with suggested colors.

**Comment by Mahitej28** [comment]
@Mayur-666 your loader is not visible to me, where exactly have you added it ? or else share the working demo here.

**Comment by Mayur-666** [comment]
> @Mayur-666 your loader is not visible to me, where exactly have you added it ? or else share the working demo here.

@Mahitej28  I have addes Loader.tsx and Loader.css files in the components folder, 
Actually i talked with @pooranjoyb  about this 

Screenshot (554)

**Comment by Mayur-666** [comment]
@Mahitej28  Please merge it, so I can work on that Protected Route feature.

**Comment by pooranjoyb** [comment]
> @Mahitej28 Please merge it, so I can work on that Protected Route feature.

Show it's working to @Mahitej28 (a screen recording would do) @Mayur-666

**Comment by Mayur-666** [comment]
Ok here is a video, for showing the loader i added new route (not pushed in PR)  just to show the working.

https://github.com/pooranjoyb/popShop/assets/118804110/6450d20a-cda8-4508-beb7-69004aa6c084

**Review by pooranjoyb — CHANGES_REQUESTED** [review]
Create a Folder called Loader, and then add the component and css file

**Comment by Mayur-666** [comment]
@pooranjoyb  Added the files in Loader named folder.

**Comment by Mayur-666** [comment]
@pooranjoyb  If you like it please merge it quick, i also want to make PR for protected route issue.

**Comment by Mayur-666** [comment]
@pooranjoyb  Please merge it, i'll get late for the Protected route thing.

**Review by pooranjoyb — APPROVED** [review]

**Pull request merged**
