### PR TITLE
update cart fetch data from supabase

### LINKED ISSUE #215: [Feat] : we can fetch cart from supabase
### Description

@pooranjoyb 

We can fetch cart items from supabase 
And display in cart page

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by dhruv8433**
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

@pooranjoyb 

[Feat] : we can fetch cart from supabase #215

Fixes #215

## Type of change

Please give a X on it which is applicable

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

- add some item in cart 
- try to go `/cart` route, all data come from supabase

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Requred)_**

# Screenshorts and Vedios:

image

give screenshorts and vedio of the changes you made

# Checklist:
give a X on it which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @dhruv8433! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
- Use the Loader component in `cart.tsx`.
- Also this should be updated. 

@dhruv8433

**Comment by dhruv8433** [comment]
ok i will do it 
@pooranjoyb

**Comment by dhruv8433** [comment]
@pooranjoyb 

i added loading skeleton: 

image

and after fetching data from database

image

**Comment by pooranjoyb** [comment]
update the cart icon too* :( @dhruv8433

**Comment by dhruv8433** [comment]
@pooranjoyb 

image

**Comment by dhruv8433** [comment]
image

**Comment by pooranjoyb** [comment]
image

it's not updating in real-time. please look into it once :) @dhruv8433

**Review by pooranjoyb — APPROVED** [review]

**Comment by dhruv8433** [comment]
@pooranjoyb 

now you can check this it update realtime

https://github.com/pooranjoyb/popShop/assets/114583978/83a817b3-f5d8-4723-a63f-af093149aff2

**Comment by pooranjoyb** [comment]
Awesome work @dhruv8433 well done 🚀

**Review by pooranjoyb — APPROVED** [review]

**Comment by dhruv8433** [comment]
@pooranjoyb 

Thank you so much bro

**Comment by pooranjoyb** [comment]
> @pooranjoyb
> 
> Thank you so much bro

Now we need to work on removing items from `Cart`. Go ahead and create an issue if you wanna work on it! 🚀

**Comment by dhruv8433** [comment]
Sure

**Pull request merged**
