### PR TITLE
Summary

### LINKED ISSUE #227: [Feature] Update `Order Summary` w.r.t cart items.
### Tasks
- Fetch items from the user's cart and render it in `Checkouts Order Summary`.
- Calculate and show the total bill.

### Screenshots

image

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by dhruv8433**
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

@pooranjoyb 

[Feature] Update Order Summary w.r.t cart items. #227

Fixes #227 (issue)

## Type of change

Please give a X on it which is applicable

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**
- go to `checkout` page

**_Test B Describe here (if Requred)_**

# Screenshorts and Vedios:

image

give screenshorts and vedio of the changes you made

# Checklist:
give a X on it which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @dhruv8433! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhruv8433** [comment]
@pooranjoyb 

please check this and merge it
if you want any modification please inform me

**Comment by pooranjoyb** [comment]
Hey @dhruv8433 maintain the initial design, no need to add images there. Just names of product and total amount would work :)

**Comment by dhruv8433** [comment]
Ok got it

**Comment by dhruv8433** [comment]
@pooranjoyb 

image

now you can merge it

**Comment by pooranjoyb** [comment]
Okay some minor changes : 

- no need of ratings
- item name and product cost should be in one line. Fix this alignment issue,
image
- Remove Tax(5%)


@dhruv8433

**Review by pooranjoyb — APPROVED** [review]

**Comment by pooranjoyb** [comment]
Convert this upto **2 decimal places** and there should be `space-between` the `Total` and `Amount` @dhruv8433

**Review by pooranjoyb — APPROVED** [review]

**Comment by dhruv8433** [comment]
Thank you @pooranjoyb

**Pull request merged**
