### PR TITLE
Fixed all the specified issues

### PR DESCRIPTION
**Pull request by Ridhima10**
Hello Pa @pooranjoyb 
Issue resolved- #205

Screenshot 2024-06-16 185826
Screenshot 2024-06-16 185856
Screenshot 2024-06-16 185936
Screenshot 2024-06-16 185752

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @Ridhima10! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
deployment failed. please run `npm run build` before pushing to github. 
Also @AjayAsnani wil review accordingly. @Ridhima10

**Comment by Mahitej28** [comment]
> deployment failed. please run `npm run build` before pushing to github. Also @AjayAsnani wil review accordingly. @Ridhima10

@Ridhima10 please run the above command your deployment has failed so we cant merge it

**Comment by Ridhima10** [comment]
@AjayAsnan
i kindly review

**Comment by pooranjoyb** [comment]
> deployment failed. please run `npm run build` before pushing to github. @Ridhima10

do this @Ridhima10

**Comment by Ridhima10** [comment]
@pooranjoyb done now

**Comment by Mahitej28** [comment]
@pooranjoyb @AjayAsnani have a look at it, looks good to me.

**Comment by pooranjoyb** [comment]
Okay so ig you broke the desktop design please check once @Ridhima10 

image

image

**Comment by Ridhima10** [comment]
Screenshot 2024-06-21 164016
Screenshot 2024-06-21 164029

**Comment by Ridhima10** [comment]
@pooranjoyb @Mahitej28  kindly review

**Comment by Ridhima10** [comment]
@pooranjoyb @Mahitej28 ??

**Comment by Mahitej28** [comment]
@AjayAsnani have a look at it.

**Comment by pooranjoyb** [comment]
The build is still failing @Ridhima10 :/

**Comment by Ridhima10** [comment]
@pooranjoyb i had fixed it days ago. Why it keeps failing? Can you suggest anything?

**Comment by pooranjoyb** [comment]
Okay shayad aapke branch me latest commits nahi hai.

Do try these.
- Run `git pull origin dev`
- Resolve any conflicts if they come up.
- Run `npm run build`
- Push updated branch. 

@Ridhima10 If the issue still persists, you can either  connect with me or mentors @Mahitej28 @AjayAsnani

**Comment by pooranjoyb** [comment]
Closing as no updates :/

**Pull request closed without merging**
