### PR TITLE
Add New popShop Logo

### LINKED ISSUE #116: [Feature] Logo for PopShop 🚀
### Description

Design the Logo for the Application and drop the Figma here in comments :)

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by me-shweta**
Fixes #116

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature 
- [ ] Refactor Code
- [ ] A documentation update
- [X] Others(Add New popShop Logo)

**Give screenshorts and vedio of the changes you made**
sdfg

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] My changes generate no new warnings

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @me-shweta! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Hii @me-shweta could you remove the `dark-yellow` background from the logo and create a `.png` for the same?

**Comment by Mahitej28** [comment]
@me-shweta kindly route the logo so that it becomes visible on the website, you need to add it in `index.html`

**Comment by me-shweta** [comment]
what did you mean by route the logo @Mahitej28 ?

**Pull request closed without merging**
