### PR TITLE
Protected Admin route added

### LINKED ISSUE #334: [Feature] Add login before access admin panel
### Description

@pooranjoyb 

we can add one username and password 
and based on that we can validate admin and get access to admin panel

### Screenshots

image

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by dhruv8433**
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

@pooranjoyb 

[Feature] Add login before access admin panel #334

Fixes #334 (issue)

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

try to navigate `/admin` route

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Requred)_**

# Screenshots and Videos:

image

it take username and password for admin login
username : admin
password: Admin@123 

Give screenshots and video of the changes you made

# Checklist:
Give a X on, which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @dhruv8433! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhruv8433** [comment]
@pooranjoyb 

kindly check this and merge it

**Comment by dhruv8433** [comment]
@pooranjoyb 

kindly please review it 
if you need any modification please inform me

**Comment by dhruv8433** [comment]
@pooranjoyb 

i created protected route for admin page
kindly please review it and merge it

**Comment by pooranjoyb** [comment]
> @pooranjoyb
> 
> i created protected route for admin page kindly please review it and merge it

 Hey I can see there are some issues.
 
 - Add a link similar to this like, Login as Admin here below the Don't you have an account?
 
image


- Remove this in Admin Login
- Add a Logout button similar to the one you created in Profile page in Admin Dashboard in the sidebar.
- It should clear the state and redirect user back to /admin route

@dhruv8433

**Comment by dhruv8433** [comment]
@pooranjoyb 

i updated my code and make it same as you said
if you think my code is good enought to get `level 3` please assign it

https://github.com/user-attachments/assets/4c92c549-2f03-473d-86f6-9377d5903c9d

**Comment by dhruv8433** [comment]
@pooranjoyb

i updated my code and make it same as you said
if you think my code is good enought to get level 3 please assign it

**Comment by dhruv8433** [comment]
@pooranjoyb

i updated my code and make it same as you said
if you think my code is good enought to get `level 3` please assign it

**Comment by dhruv8433** [comment]
@pooranjoyb 

please response 
i request you kindly check this and merge it

**Comment by pooranjoyb** [comment]
Hii @dhruv8433 i am travelling today will review and merge tomorrow.

**Comment by dhruv8433** [comment]
ok thank you for response

**Comment by dhruv8433** [comment]
@pooranjoyb 

when you become free, please check this and merge it

**Pull request merged**
