### PR TITLE
changes for styling by ChelseaSingla1

### PR DESCRIPTION
**Pull request by Chelseasingla1**
I made changes according to #19 issue
I added a new button in Routes.tsx for styling 
And made a new page Styling path is /home/styling
image
image

image

First there is no styled outfit
Once user click on above products to style different clothing's it would be visible like this:
image

Here is the video tutorial:
[**Video Demonstration how this styling page actually works**](https://youtu.be/FdBeZWbNUvU)

We can make changes by adding multiple images mean time i have only added three images

### CODE REVIEW

**Comment by pooranjoyb** [comment]
Hii @Chelseasingla1 Take a Pull from the master branch, there are some changes in the `Auth.tsx` .
Hence, the build failed.

**Comment by Chelseasingla1** [comment]
> Hii @Chelseasingla1 Take a Pull from the master branch, there are some changes in the `Auth.tsx` . Hence, the build failed.

@pooranjoyb Hi this is little confusing it was written to take pull request from dev branch, was i not suppose to do that and now i need to pull it from main branch right?

**Comment by pooranjoyb** [comment]
> > Hii @Chelseasingla1 Take a Pull from the master branch, there are some changes in the `Auth.tsx` . Hence, the build failed.
> 
> @pooranjoyb Hi this is little confusing it was written to take pull request from dev branch, was i not suppose to do that and now i need to pull it from main branch right? 

You can take a pull again from `dev` or `master`. No issues, both are updated to HEAD. 

Actually there were some build errors due to a PR, thats why we had to do some changes in the master as well dev. You can just take a pull, possibly wont be any merge conflicts. Push a commit for that merge then @Mahitej28 will guide through the responsiveness.

**Comment by Chelseasingla1** [comment]
> > > Hii @Chelseasingla1 Take a Pull from the master branch, there are some changes in the `Auth.tsx` . Hence, the build failed.
> > 
> > 
> > @pooranjoyb Hi this is little confusing it was written to take pull request from dev branch, was i not suppose to do that and now i need to pull it from main branch right?
> 
> You can take a pull again from `dev` or `master`. No issues, both are updated to HEAD.
> 
> Actually there were some build errors due to a PR, thats why we had to do some changes in the master as well dev. You can just take a pull, possibly wont be any merge conflicts. Push a commit for that merge then @Mahitej28 will guide through the responsiveness.

@pooranjoyb Okay sir thankyou will that do asap.

**Comment by Mahitej28** [comment]
@Chelseasingla1 let me know if you need any help

**Pull request closed without merging**
