### PR TITLE
[Feature] Enhance Authentication Screen #156

### PR DESCRIPTION
**Pull request by richab246**
Updated Login and Signup frontend

Fixes # #156

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [✅ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?
Just updated the current code with better features

# Screenshorts and Vedios:
Screenshot 2024-06-03 162810

Screenshot 2024-06-03 162841

Screenshot 2024-06-03 162904

# Checklist:
give a X on it which is applicable

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @richab246! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Awesome work @richab246 🚀 
But it seems like some of the design elements are breaking in Home and subsequent pages.
I mean the new button design is pretty cool but maintain the width in the Home page also.

Please so the following changes.

- Add the Reset Button in Forgot Password section.
- Home page `Cart icon` is invisible

image
- Width issue of button.

image
- same issue in `Cart`.

image
- Same in `Profile`

image


Just fix these things and we are good to go for the merge. @richab246

**Comment by richab246** [comment]
I did all the changes you told @pooranjoyb

**Comment by pooranjoyb** [comment]
Awesome work @richab246 
Would be glad to see you contributing in other issues too! 
Happy Coding :)

**Pull request merged**
