### PR TITLE
Profile UI

### LINKED ISSUE #269: [Feature] Ui for `Profile` Page
### Description

@pooranjoyb 

we can design beautiful ui for profile route

### Screenshots

image

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by dhruv8433**
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

@pooranjoyb 

[Feature] Ui for Profile Page #269

Fixes #269 (issue)

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

go to `/profile` route

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Requred)_**

# Screenshots and Videos:

image

image

image

image

Give screenshots and video of the changes you made

# Checklist:
Give a X on, which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pooranjoyb — COMMENTED** [review]
Great job, @dhruv8433! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhruv8433** [comment]
@pooranjoyb 

kindly check this and merge it

**Comment by pooranjoyb** [comment]
Well, it's not looking that good tbh. You can see that the Footer makes it even worse for this design. Also the Text Box for User details doesn't look that good. Please do some modifications for the same @dhruv8433

**Comment by dhruv8433** [comment]
@pooranjoyb 

kindly check this and if you need any modifications, please inform me

image

**Comment by pooranjoyb** [comment]
Okay @dhruv8433 

here are some changes you need to do : 

- Remove the Footer in profile page
- Remove subscription wala section too.
- This heading as User Profile doesnot makes sense as we already have the Logo there. (Remove it)

image

- Keeping both the sidebar and dropdown in the profile icon doesnot makes sense. 

image

I mean better keep the links of the profile icon on the sidebar itself

- Also you see the bg is not looking good, it should be stick to the top behind the navbar like before.
- If the sidebar is there, it should be of a proper theme color. do that too.
- Remove this entire thing in mobile version

image

**Comment by dhruv8433** [comment]
Okay @pooranjoyb

**Comment by dhruv8433** [comment]
@pooranjoyb 

image

image

**Comment by dhruv8433** [comment]
@pooranjoyb 

kindly please review it and merge it

**Comment by dhruv8433** [comment]
@pooranjoyb

kindly please review it and merge it

**Comment by pooranjoyb** [comment]
Logout button ko bottom corner me laga do :) @dhruv8433

**Comment by dhruv8433** [comment]
@pooranjoyb 

check this out,

image

**Comment by pooranjoyb** [comment]
Text center in Logout :/

**Comment by dhruv8433** [comment]
@pooranjoyb 

image

**Comment by dhruv8433** [comment]
@pooranjoyb 

i updated my code and center logout text
can you please review it and merge it

**Comment by dhruv8433** [comment]
@pooranjoyb

i updated my code and center logout text
can you please review it and merge it

**Comment by dhruv8433** [comment]
@pooranjoyb 

kindly please review it 
if you need any modification please inform me

**Comment by dhruv8433** [comment]
@pooranjoyb 

please review it and merge it so i can work on other issue
and if you need any modification please inform me

i already changed my code as you said

**Comment by dhruv8433** [comment]
@pooranjoyb 

please merge it before gssoc end
and it also creates conflicts 

please merge it

**Comment by dhruv8433** [comment]
@pooranjoyb 

Please merge it before gssoc end 
I think it's 30 jul ...

**Comment by pooranjoyb** [comment]
> @pooranjoyb
> 
> Please merge it before gssoc end I think it's 30 jul ...

Yes, actually had a discussion with the mentors, this one actually didn't get approved properly as this doesnot look that good uk. Still i will merge this in different branch tho :)

**Comment by dhruv8433** [comment]
@pooranjoyb 

please tell me if you need any changes 
please merge it .... :/

**Comment by dhruv8433** [comment]
@pooranjoyb 

please sir response
today is last day and you told me that you can merge this pr 

please sir check into this

**Comment by dhruv8433** [comment]
@pooranjoyb 

i resolve all conflicts now please merge this into any other branch

**Pull request merged**
